Update adding page items logic
MobileUpLLC/ListController pull request #6
Opened 2022-01-10 13:03 UTC by timonity

2022-01-10 13:28 UTC, VGrokhotov commented on Example/Source/UI/Pagination/CustomPagingTableViewController.swift
>          super.handlePagingError(error)
nit: Если хотим так писать (а мы хотим писать именно так, вроде), то из класса `PagingTableViewController` нужно убрать 116-ую строчку (в соответсвии со строчкой 63 в том же файле)

2022-01-10 13:29 UTC, VGrokhotov commented on Sources/LoadingTableViewController/PagingAdapter.swift
> +    private var _isEnabled: Bool = false
nit: убрать бы как-то "_", но я сам не знаю как

2022-01-10 13:31 UTC, VGrokhotov approved these changes

2022-01-10 13:35 UTC, VGrokhotov commented
LGTM, но человеку не в контексте будет не понятно, почему именно так все сделано, неочевидно как-то, но это, скорее всего, не так важно

2022-01-10 14:01 UTC, VGrokhotov commented on Sources/LoadingTableViewController/PagingAdapter.swift
> +    private var _isEnabled: Bool = false
```swift
public var isEnabled: Bool {
        didSet {
            if isEnabled && !oldValue {
                enable()
            } else if !isEnabled && oldValue {
                disable()
            }
        }
    }
```

2022-01-10 14:05 UTC, VGrokhotov requested changes

2022-01-10 14:05 UTC, VGrokhotov commented on Sources/LoadingTableViewController/PagingAdapter.swift
> +    private var _isEnabled: Bool = false
```swift
public var isEnabled: Bool {
    didSet {
        if isEnabled && !oldValue {
            enable()
        } else if !isEnabled && oldValue {
            disable()
        }
    }
}
```

2022-01-10 14:15 UTC, VGrokhotov requested changes

2022-01-10 14:15 UTC, VGrokhotov commented on Sources/LoadingTableViewController/PagingAdapter.swift
>      public var isEnabled: Bool {
```swift
public var isEnabled: Bool {
    didSet {
        if isEnabled && !oldValue {
            enable()
        } else if !isEnabled && oldValue {
            disable()
        }
    }
}
```

2022-01-11 09:42 UTC, timonity commented on Example/Source/UI/Pagination/CustomPagingTableViewController.swift
>          super.handlePagingError(error)
+

2022-01-11 09:42 UTC, timonity commented on Sources/LoadingTableViewController/PagingAdapter.swift
>      public var isEnabled: Bool {
+

2022-01-11 09:44 UTC, timonity commented on Sources/LoadingTableViewController/PagingAdapter.swift
> +    private var _isEnabled: Bool = false
Done

2022-01-11 10:26 UTC, VGrokhotov approved these changes

2022-01-11 11:08 UTC, merged